### ISSUE TITLE
Multiple major revs in `hashes` dependency doesn't work the way I expected

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#673]
This library currently supports `hashes` 0.12 or 0.13. The point was that you can use this library alongside rust-bitcoin 0.30 (which depends on 0.12) or rust-bitcoin 0.31 (which depends on 0.13). You wouldn't want to do this permanently -- it's for the upgrade process between major revs of rust-bitcoin, so that you can update your various deps piecemeal and things will continue to work.

**However**, cargo will cheerfully allow (and may actually do, by default) you to have rust-secp depending on hashes 0.12 **in the same tree** as rust-bitcoin depending on hashes 0.13. Then the `ThirtyTwoByteHash` traits will be incompatible and you'll get compilation errors.

Our intention was "rust-secp256k1 supports whatever version of hashes rust-bitcoin is trying to use" but apparently we can't guide cargo into enforcing this :/.

**Comment by Kixunil** [comment]
Oh, right that actually makes sense even though it took me a bit to understand. The situation cannot be solved otherwise if you have two different `bitcoin` versions. I see two possible solutions:

* Have a separate micro-crate for the trait and stabilize it practically immediately
* Have versioned hashes feature (`bitcoin_hashes_0_12`, `bitcoin_hashes_0_13`), then `bitcoin` depends on the version of `hashes` it supports and when you turn on both the trait is implemented for both so everything works.

**Comment by apoelstra** [comment]
I don't like the idea of having micro-crates because we'd wind up with a ton of them, which may be formally "stable" but probably we'd be constantly creating and abondoning them.

Versioned features *might* work ... it's a little ugly, but I think it'd solve this particular upgrade path.

**Comment by Kixunil** [comment]
Well, in this case I also prefer not doing a micro crate since we want to stabilize things ~soon anyway.

**Comment by tcharding** [comment]
Ha! stablizing secp is literally years away. What if we were to move `ThirtyTwoByteHash` to `hashes` and then we can use the semver trick - well at least I think we can. If there are no obvious problems I'll have a go, will wait to see if this gets shot down first though.

**Comment by Kixunil** [comment]
The trait is not the only reason for the `hashes` feature. I wish it was. Hashing is actually used (in ECDH IIRC).

> stablizing secp is literally years away.

Is it? I thought removing contexts and improving errors is enough. If I'm wrong we'll have to seriously rethink APIs in `bitcoin`.

**Comment by apoelstra** [comment]
>The trait is not the only reason for the hashes feature. I wish it was. Hashing is actually used (in ECDH IIRC).

Right, but the trait is the only part of `hashes` exposed in the public API. And it's a weird trait that straddles rust-secp and bitcoin_hashes.

+1 to moving it to bitcoin_hashes and semver tricking it, *except* that I think the transition will be a big PITA and maybe it's not worth the pain.

>Ha! stablizing secp is literally years away.

For rust-secp I think we just have a couple things, as Kix says. For libsecp itself, you're correct that they'll continue to have new versions for years, which we need to keep up with for security reasons but which may break our APIs (meaning we need to avoid exposing them except by feature gates that are clearly marked "unstable"). I think we can manage that.

**Comment by Kixunil** [comment]
I mean it's impossible to move it to hashes because it'd create a circular dependency. (Also I strongly believe secp is the proper place for it if there's no specialized crate.)

**Comment by apoelstra** [comment]
I don't think it'd create a circular dependency, but we'd have to keep the `impl`s in rust-secp, which might not actually improve anything as far as version compatibility went.

**Comment by Kixunil** [comment]
For trait: hashes -> secp
For ECDH: secp -> hashes

**Comment by tcharding** [comment]
I'll just hack it up and solve this one way or the other :)

**Comment by apoelstra** [comment]
@Kixunil the trait doesn't require `hashes` to depend on `secp`. It's just a trait definition that specifies that you can convert a blob to a [u8; 32] and has a promise about being a cryptographic commitment.

**Comment by Kixunil** [comment]
Oh, I don't know why I was thinking it does need to. Probably confused by orphan rules or something.

**Comment by tcharding** [comment]
BOOM! It works. I'll write what I did from memory, it was convoluted so I probably need to write it out and re-do the whole thing before we do it for real. Requires one patch to `rust-bitcoin` that does not build. Some things I used manifest patching and some steps I pushed branches to github.

1. Move the trait from secp to hashes
1. Do a hashes 0.14.0 release (**`rust-bitcoin` does not build on this patch**)
1. Upgrade secp to use hashes 0.14
1. Create branch `hashes-0.14.x` on `rust-bitcoin` repo
1. Do a hashes 0.15 release (no changes,  just to prove the semver trick works).
1. Do a hashes 0.14.1 release on branch `hashes-0.14.x` (add semver trick).

**Comment by Kixunil** [comment]
Since this is super annoying and hashes-API-breaking, can we do it together with https://github.com/rust-bitcoin/rust-bitcoin/pull/1555 ?

**Comment by apoelstra** [comment]
Yeah, I'd like to do it alongside #1555. And maybe we can combine them, and use the new "digest" trait in place of `ThirtyTwoByteHash`.

**Comment by tcharding** [comment]
> Then the ThirtyTwoByteHash traits will be incompatible and you'll get compilation errors.

I don't think this is the case anymore because `ThirtyTwoByteHash` is only used by `Message::from` which is only used by the three hashes in `sighash`, ie, `hashes` doesn't touch it.

**Comment by tcharding** [comment]
I _think_ we used to implement `ThirtyTwoByteHash` for all hashes in `hashes` module and that caused the pain.

**Comment by apoelstra** [comment]
Ahh, interesting. So, we **do** still implement `ThirtyTwoByteHash` for the types in `hashes`, and we do it in rust-secp itself (since `hashes` can't do it due to coherency rules). This is what causes problems with multiple version of `hashes`.

But maybe we can drop those impls now, if rust-bitcoin defines sighash types and implements `ThirtyTwoByteHash` for those. I believe this would also fix the "dependency hole" problems we've had in the past.

Arguably we should drop the trait entirely and just have inherent methods on the sighash types. Or use `Into<Message>` instead of a custom trait.

**Comment by apoelstra** [comment]
I think, for the sake of getting this release out, we should remove the impls in rust-secp (and close this issue). So then `ThirtyTwoByteHash` becomes just a dumb trait with no implementors.

Later we can discuss removing the trait entirely.

**Comment by apoelstra** [comment]
Yes, you will get compilation errors. For example, if you try to use the `ThirtyTwoByteHash` trait on `bitcoin::hashes::sha256::Hash`, you will find that this compiles if both bitcoin and secp256k1 have the same version of `hashes`, and does not compile otherwise.

**Comment by tcharding** [comment]
Oh yeah of course, I thought you meant we will get compilation errors _now_ in `rust-bitcoin`.

**Comment by apoelstra** [comment]
No, only users of rust-bitcoin will get compilation errors.

**Comment by Kixunil** [comment]
I'm completely confused now. If the trait moves to hashes how can secp256k1 implement it for hashes?

**Comment by apoelstra** [comment]
@Kixunil where we landed is:

* The trait stays here (though I'd like to change it to just `Into<Message>` with appropriate documentation that users should not ever implement this for somthing that is not a cryptographic hash and especially something that might be all zeroes.
* We drop the impls on the "bare" hash types sha256 etc. In rust-bitcoin we currently implement this trait for the `*SigHash` types and we should recommend users do the same (define their own hash to represent the kind of message they expect to be signed, using our convenient "define your own hash" macros).

Then rust-secp is depending on `hashes` only for ECDH, which does not expose any hash types in its API, and then it doesn't matter what version rust-secp is using.

But to answer your question
>I'm completely confused now. If the trait moves to hashes how can secp256k1 implement it for hashes?

If the trait moved to hashes then *hashes* would be responsible for implementing it for hashes.
