### PR TITLE
Update the code to edition 2018, and update dependencies

### PR DESCRIPTION
**Pull request by elichai**
As proposed in https://github.com/rust-bitcoin/rust-bitcoin/issues/510#issuecomment-881686342 this PR raises the MSRV to 1.36.0, it also changes the code to be Edition 2018.

The PR contains a few things:
* Moving to edition 2018 and fixing the imports
* Sorting and combining imports to make them more concise
* Replacing our c_void with `core::ffi::c_void`
* Bumping the `rand` version to latest and modifying our `RngCore` implementations accordingly
* Doing some small refactoring and using the new `TryInto` trait where it makes the code nicer

If people prefer I can split this PR into multiple and/or drop some commits

### CODE REVIEW

File: secp256k1-sys/src/macros.rs [hunk 1]
```diff
@@ -93,41 +93,41 @@ macro_rules! impl_array_newtype {
...
             #[inline]
-            fn index(&self, index: ::core::ops::Range<usize>) -> &[$ty] {
+            fn index(&self, index: core::ops::Range<usize>) -> &[$ty] {
                 let &$thing(ref dat) = self;
                 &dat[index]
             }
         }
 
-        impl ::core::ops::Index<::core::ops::RangeTo<usize>> for $thing {
+        impl core::ops::Index<::core::ops::RangeTo<usize>> for $thing {
```
Comment (RCasatta) [inline secp256k1-sys/src/macros.rs:106]: missing one `::`

File: .github/workflows/rust.yml [hunk 2]
```diff
@@ -60,7 +60,7 @@ jobs:
     strategy:
       matrix:
         rust:
-          - 1.29.0
```
Comment (thomaseizinger) [inline .github/workflows/rust.yml:63]: If we want CI to pass with all commits, this one should go to the very front of the PR.

**Review by thomaseizinger — COMMENTED** [review]
Thank you for doing this, looking forward to dropping old rand dependencies in our project :)

File: src/lib.rs [hunk 3]
```diff
@@ -1295,6 +1293,32 @@ mod tests {
...
+            // and it doesn't matter much if it will vary per architecture.
+            let rand = self.next_u64().to_ne_bytes();
+            chunk.copy_from_slice(&rand[..chunk.len()]);
+        }
+    }
+
+    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand::Error> {
+        Ok(self.fill_bytes(dest))
+    }
+}
```
[the remark this answers is not in the document]
Comment (elichai) [reply src/lib.rs:1322]: Yes! I did not know about that, Thanks :)

File: secp256k1-sys/src/lib.rs [hunk 4]
```diff
@@ -537,10 +539,10 @@ extern "C" {
 // Returns: a newly created context object.
 //  In:      flags: which parts of the context to initialize.
 #[no_mangle]
-#[cfg(all(feature = "std", not(rust_secp_no_symbol_renaming)))]
+#[cfg(all(feature = "alloc", not(rust_secp_no_symbol_renaming)))]
 pub unsafe extern "C" fn rustsecp256k1_v0_4_1_context_create(flags: c_uint) -> *mut Context {
     use core::mem;
-    use std::alloc;
+    use crate::alloc::alloc;
```
[the remark this answers is not in the document]
Comment (elichai) [reply secp256k1-sys/src/lib.rs:545]: It complains in rust 1.36, I'm not fully understanding why,
Try the following
```bash
echo '#![no_std]
extern crate alloc;
use alloc::alloc;' > /tmp/test.rs
rustc +1.36.0 /tmp/test.rs
```

Error:
```rust
error[E0254]: the name `alloc` is defined multiple times
 --> /tmp/test.rs:3:5
  |
2 | extern crate alloc;
  | ------------------- previous import of the extern crate `alloc` here
3 | use alloc::alloc;
  |     ^^^^^^^^^^^^ `alloc` reimported here
  |
  = note: `alloc` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
  |
3 | use alloc::alloc as other_alloc;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

[the remark this answers is not in the document]
Comment (elichai) [reply secp256k1-sys/src/lib.rs:545]: Argh never mind, this seems to be a different error

[the remark this answers is not in the document]
Comment (elichai) [reply secp256k1-sys/src/lib.rs:545]: I'm not quite sure, it works on latest, but on rust 1.36.0 it gives me the following error:
```rust
error[E0659]: `alloc` is ambiguous (name vs any other name during import resolution)
  --> src/context.rs:96:9
   |
96 |     use alloc::alloc;
   |         ^^^^^ ambiguous name
   |
note: `alloc` could refer to the module imported here
  --> src/context.rs:96:9
   |
96 |     use alloc::alloc;
   |         ^^^^^^^^^^^^
   = help: use `self::alloc` to refer to this module unambiguously
note: `alloc` could also refer to the extern crate imported here
  --> src/lib.rs:120:27
   |
120| #[cfg(feature = "alloc")] extern crate alloc;
   |                           ^^^^^^^^^^^^^^^^^^^
   = help: use `::alloc` to refer to this extern crate unambiguously
```

[the remark this answers is not in the document]
Comment (elichai) [reply secp256k1-sys/src/lib.rs:545]: like the import can somehow refer to itself?

File: secp256k1-sys/src/macros.rs (hunk 1 above)
Comment (elichai) [reply secp256k1-sys/src/macros.rs]: Done, Thanks!

File: examples/generate_keys.rs [hunk 5]
```diff
@@ -5,7 +5,7 @@ use secp256k1::{PublicKey, Secp256k1, SecretKey};
 
 fn main() {
     let secp = Secp256k1::new();
-    let mut rng = OsRng::new().unwrap();
+    let mut rng = OsRng;
```
[the remark this answers is not in the document]
Comment (elichai) [reply examples/generate_keys.rs]: Done

File: .github/workflows/rust.yml (hunk 2 above)
Comment (elichai) [reply .github/workflows/rust.yml:63]: Done, Thanks for noticing :)

File: secp256k1-sys/src/lib.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (thomaseizinger) [reply secp256k1-sys/src/lib.rs:545]: Fair enough :man_shrugging:

**Review by thomaseizinger — COMMENTED** [review]
ACK e6dc0b27f65a4f7520d964200b7a259a9795f298

**Comment by Kixunil** [comment]
Didn't review but I randomly noticed that we could change [`CONTEXT`](https://github.com/rust-bitcoin/rust-secp256k1/blob/master/src/context.rs#L37) from `Option` to `MaybeUninit`.

**Comment by apoelstra** [comment]
Cool! concept ACK. Will review in detail later.

I think there is nothing stopping us merging this now? For rust-bitcoin I want a taproot release before the 2018 release, but I believe we don't need any further supporting changes from rust-secp for Taproot?

File: src/key.rs [hunk 6]
```diff
@@ -125,9 +127,8 @@ impl SecretKey {
     /// Converts a `SECRET_KEY_SIZE`-byte slice to a secret key
     #[inline]
     pub fn from_slice(data: &[u8])-> Result<SecretKey, Error> {
-        match data.len() {
-            constants::SECRET_KEY_SIZE => {
-                let mut ret = [0; constants::SECRET_KEY_SIZE];
+        match <[u8; constants::SECRET_KEY_SIZE]>::try_from(data) {
```
Comment (Kixunil) [inline src/key.rs:130]: In general `TryFrom` should be used to **implement** fallible conversion, `try_into()` to **call** fallible conversion. (because `TryFrom` implies `TryInto`) I think it's OK when the types are not generic but maybe keeping the good habit is worth changing?

Comment (dr-orlovsky) [reply src/key.rs:130]: IMHO `try_into` hides information into which specific type the conversion happens and makes code less readable / verifiable by human

Comment (thomaseizinger) [reply src/key.rs:130]: @kixonil I don't think that is generally true. AFAIK it is idiomatic to prefer `TryInto` over `TryFrom` but if you are not doing trait-bounds at all, `TryFrom` might be better because it doesn't need type annotations.

Comment (Kixunil) [reply src/key.rs:130]: This is possible:

```rust
let x: Type = y.try_into()?;
```

But I think `TryFrom` is OK in this case.

**Comment by apoelstra** [comment]
We do actually need to do a rust-secp release for Taproot, so delaying this until the next major rev.

Also, needs rebase.

**Comment by tcharding** [comment]
In case you want to save yourself some work @elichai I was playing around with this branch and it took me quite a while to rebase it. Feel free to grab what I have done to save yourself having to do it. Same branch name on my tree (`github.com/tcharding/rust-secp256k1`).

**Comment by tcharding** [comment]
I've had a git fail the other day @elichai and pushed to your branch. Super sorry about that, I did not realize `pushRemote = git@github.com:elichai/rust-secp256k1.git` was set in my config. FTR I checked out your branch using `gh pr` (github's command line tool). I assumed the branch would be configured to push to origin, I was wrong. I feel pretty rude having done that, please accept my apologies.

**Comment by tcharding** [comment]
Anyways, there is a branch on my tree now that has been updated to do two things
- Use Rust 1.41.1
- Try to make the diff as small and easy to review as possible (mainly this means not moving the import statements around anymore than is necessary).

**Comment by elichai** [comment]
> 

No you didn't push here, Thanks for your rebase it helped to make sure I'm rebasing correctly (still rebased myself as to know what actually changed)

>     * Use Rust 1.41.1


Does that change anything here?

**Comment by tcharding** [comment]
> Does that change anything here?

Does not change the patch set AFAICT except for the actual version number itself and the commit messages.

**Comment by tcharding** [comment]
Hey @elichai, no clue what order the MSRV patches are going to merge across the rust-bitcoin stack but we are in the vicinity of ready to merge this one, have you time to update the PR?

**Comment by tcharding** [comment]
I was messing around with https://github.com/rust-bitcoin/rust-bitcoin/pull/967 and chased build errors into secp, then into `rand` and ended up rebasing my local copy of this PR to see if it was a rand 6 problem. Anyways, in case its of any use I pushed it up to my tree on a branch of the same name again. FTR I'm hitting a build error still when enabling `use-serde` (on rust-bitcoin), but anyways there it is :)

**Comment by elichai** [comment]
> Hey @elichai, no clue what order the MSRV patches are going to merge across the rust-bitcoin stack but we are in the vicinity of ready to merge this one, have you time to update the PR?

I'll rebase today-tomorrow

**Comment by Kixunil** [comment]
@elichai since it's platform-gated it should be fine, I think, even more so since it's dev dependency.

File: secp256k1-sys/src/recovery.rs [hunk 7]
```diff
@@ -170,6 +167,6 @@ mod fuzz_dummy {
         1
     }
 }
-#[cfg(fuzzing)]
-pub use self::fuzz_dummy::*;
 
+#[cfg(fuzzing)]
+pub use self::fuzz_dummy::*;
```
Comment (thomaseizinger) [inline secp256k1-sys/src/recovery.rs:172]: Nit: Newline at EOF got dropped here.

**Review by thomaseizinger — APPROVED** [review]
utACK 63de67fecf44b5f909793cbde9a2db22fa7d119f

Excited to see this land!

**Comment by thomaseizinger** [comment]
I guess 63de67fecf44b5f909793cbde9a2db22fa7d119f could be squashed into the rand upgrade commit?

File: .github/workflows/rust.yml [hunk 8]
```diff
@@ -59,7 +56,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        rust: [stable, beta, nightly] # No 1.29 because WASM requires Rust 1.30
+        rust: [stable, beta, nightly] # wasm-pack doesn't support rust 1.41
```
Comment (tcharding) [inline .github/workflows/rust.yml:59]: To be pedantic but lazy, I think we should use 1.41.1 everywhere, saves trying to work out if it matters in each situation we use it.

File: README.md [hunk 9]
```diff
@@ -20,21 +20,7 @@ Contributions to this library are welcome. A few guidelines:
...
-with `cargo update -p cc --precise 1.0.41`. If you're using `secp256k1` in a library,
-to make sure it compiles in CI, you'll need to generate a lockfile first.
-Example for Travis CI:
-```yml
-before_script:
-  - if [ "$TRAVIS_RUST_VERSION" == "1.29.0" ]; then
-    cargo generate-lockfile --verbose && cargo update -p cc --precise "1.0.41" --verbose;
-    fi
-```
+* This library should always compile with any combination of features on **Rust 1.41**.
```
Comment (tcharding) [inline README.md:23]: And here, like other comment, 1.41.1

File: clippy.toml [hunk 10]
```diff
@@ -1 +1 @@
-msrv = "1.29"
+msrv = "1.41"
```
Comment (tcharding) [inline clippy.toml:1]: And here.

File: src/ecdsa/recovery.rs [hunk 11]
```diff
@@ -237,7 +235,9 @@ impl<C: Verification> Secp256k1<C> {
 mod tests {
     use super::*;
     use rand::{RngCore, thread_rng};
-    use key::SecretKey;
+
+    use crate::{SecretKey, Secp256k1, Message};
+    use super::{RecoveryId, RecoverableSignature};
```
Comment (tcharding) [inline src/ecdsa/recovery.rs:240]: We don't need this one, have wildcard above.

File: src/lib.rs [hunk 12]
```diff
@@ -150,47 +149,19 @@
...
-#![deny(non_upper_case_globals)]
-#![deny(non_camel_case_types)]
-#![deny(non_snake_case)]
-#![deny(unused_mut)]
-#![warn(missing_docs)]
-#![warn(missing_copy_implementations)]
-#![warn(missing_debug_implementations)]
-
+#![deny(non_upper_case_globals, non_camel_case_types, non_snake_case)]
+#![warn(missing_docs, missing_copy_implementations, missing_debug_implementations)]
```
Comment (tcharding) [inline src/lib.rs:153]: No action required, just my opinion, I rekon this is less readable.

File: src/secret.rs [hunk 13]
```diff
@@ -14,25 +14,23 @@
 
 //! Helpers for displaying secret values
 
-use ::core::fmt;
-use ::{SecretKey, KeyPair, to_hex};
-use ecdh::SharedSecret;
-use constants::SECRET_KEY_SIZE;
-
+use core::fmt;
+use crate::{to_hex, constants::SECRET_KEY_SIZE, key::{SecretKey, KeyPair}, ecdh::SharedSecret};
```
Comment (tcharding) [inline src/secret.rs:18]: This import statement is not uniform with the rest of the crate but lets ignore it for now and let the tooling sort it out later. I have various active efforts to resolve the `rustfmt` usage issue across the stack :)

**Review by tcharding — DISMISSED** [review]
ACK 63de67fecf44b5f909793cbde9a2db22fa7d119f

Thanks for rebasing, these edition PRs are not that exciting to do but the PR landing is super exciting. All my comments are nits, please don't see to any of them unless you are rebasing for some other reason. Lets get this in as quick as we can and fix up later, there is tons of clean up to do after this anyways. Cheers

File: src/secret.rs (hunk 13 above)
Comment (elichai) [reply src/secret.rs:18]: I'd love to use rustfmt for these kinds of things(with default configuration or not), although sadly it doesn't currently merge imports together. 
Either way, we should probably come up with some styling guide for rust-bitcoin, as currently I feel like different people prefer different things and then it's not consistent across the code base

Comment (tcharding) [reply src/secret.rs:18]: Fair point. AFAIU there is an unstable config option for this
`
imports_granularity = "Module"     # Default "Preserve"
```

I personally prefer the "Module" option because it makes, in my experience, for less noisy diffs as imports are added and removed. I'm trying to slowly resolve the rustfmt issue atm.

**Comment by apoelstra** [comment]
Should get #439 in first; and needs rebase again.

File: src/secret.rs (hunk 13 above)
Comment (thomaseizinger) [reply src/secret.rs:18]: > unstable config option

There is a useful[^1] bug in rustfmt where you can pass unstable config options via the commandline without needing nightly!

e.g. the following works with stable rustfmt (if you delete the rustfmt file that disables everything):

```shell
cargo fmt -- --config imports_granularity=module
```

You could piece together a rustfmt config using [aliases](https://doc.rust-lang.org/cargo/reference/config.html#configuration-format) that handpicks the options you want but also makes them easily accessible for CI and local development.

Editors won't pick that up unfortunately though.

[^1]: Useful because needing to install a nightly toolchain just for formatting is stupid IMO.

Comment (tcharding) [reply src/secret.rs:18]: Thanks for the tip, not working with an editor is not really acceptable IMO.

**Comment by elichai** [comment]
First push is a rebase, and the second one is fixing the nits

File: src/key.rs [hunk 14]
```diff
@@ -162,9 +163,8 @@ impl SecretKey {
     /// ```
     #[inline]
     pub fn from_slice(data: &[u8])-> Result<SecretKey, Error> {
-        match data.len() {
```
Comment (apoelstra) [inline src/key.rs:169]: In ac8e966ab5c4b0e6eb3c918e283aff0d3883427b:

Maybe worth thinking about turning these `from_slice` methods into `TryFrom` impls entirely ... doesn't need to be in this PR.

**Review by apoelstra — DISMISSED** [review]
ACK 2f18866ab7648ceed76e7fa46bdba44a93ad66f9 aside from nits

**Review by tcharding — APPROVED** [review]
ACK 2f18866ab7648ceed76e7fa46bdba44a93ad66f9

**Comment by tcharding** [comment]
Oh, @elichai, I just noticed the PR description mentions 1.36 still.

**Comment by tcharding** [comment]
This is the last on to go and we have done it, friendly bump please reviewers :)

File: src/schnorr.rs [hunk 15]
```diff
@@ -139,8 +135,7 @@ impl<C: Signing> Secp256k1<C> {
     #[cfg(any(test, feature = "rand-std"))]
     #[cfg_attr(docsrs, doc(cfg(feature = "rand-std")))]
     pub fn sign_schnorr(&self, msg: &Message, keypair: &KeyPair) -> Signature {
-        let mut rng = thread_rng();
-        self.sign_schnorr_with_rng(msg, keypair, &mut rng)
+        self.schnorrsig_sign_with_rng(msg, keypair, &mut rand::thread_rng())
```
[the remark this answers is not in the document]
Comment (apoelstra) [reply src/schnorr.rs:138]: IMO this is blocking merge.

File: src/key.rs (hunk 14 above)
Comment (tcharding) [reply src/key.rs:169]: FWIW I rekon we should keep this PR as lean as possible to help expedite review/merge.

**Comment by koushiro** [comment]
Hi, can I ask when this PR is planned to be merged and a new version containing the PR will be released?

**Comment by Kixunil** [comment]
@koushiro wehope for it to be faster than usual but it'll probably still take some time.

File: src/schnorr.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (apoelstra) [reply src/schnorr.rs:138]: @elichai I am happy to merge this once you address this

**Comment by tcharding** [comment]
As far as I understand it, soon as this PR merges we can start releasing each of the crates in the rust-bitcoin stack starting at the bottom. `rust-bech32` has been done already so next its `rust-bitcoinconsensus`, then `bitcoin_hashes` then this one. Hope that helps explain the process and potential timing.

**Comment by tcharding** [comment]
Friendly bump, can we get an ack on this from another maintainer please. (I don't actually know who are the maintainers of this crate? @real-or-random, @jonasnick). Is that what you are waiting for to merge this @apoelstra?

**Comment by apoelstra** [comment]
I am waiting for the use of `self.schnorrsig_sign_with_rng` to be removed.

File: src/schnorr.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (elichai) [reply src/schnorr.rs]: Sorry, missed the notification on this

**Comment by elichai** [comment]
Fixed, sorry that it took me so long

**Review by tcharding — APPROVED** [review]
ACK 5d2f1ceb641e2d2cb61f4fa3a33dfce179e3d47b
